#!/bin/bash -l

P=(1 2 4 8 16 32 56)
N=(4000)
num_nodes=1
module purge
module load gcc openblas mvapich2
make clean 
make

filename=weak_scaling.txt

#rm $filename
#echo "processors,n,time" >> $filename

for iter in {1..4}
do
num_nodes=1
for p in ${P[@]}
do
    for n in ${N[@]}
    do 
    if [ $p -ge 16 ];  then num_nodes=2; fi
        echo "Run $p processes on $num_nodes nodes"
        srun  -A sds --nodes $num_nodes --time=0:0:5  -n $p ./cgsolver lap2D_5pt_n100.mtx $n >> $filename &
    done
done
done 