#!/bin/bash -l

P=(1 2 4 8 16 32 56)
num_nodes=1
module purge
module load gcc openblas mvapich2
make clean 
make

filename=strong_scaling.txt

rm $filename
echo "processors,n,time" >> $filename

for p in ${P[@]}
do
    if [ $p -ge 16 ];  then num_nodes=2; fi
        echo "Run $p processes on $num_nodes nodes"
        srun  --reservation=Course-math-454 -A math-454 --nodes $num_nodes  -n $p ./cgsolver $p >> $filename &
done